version: "3.5"

services:
  database:
    restart: on-failure:1
    container_name: vic-db
    build:
      context: api/db
    env_file: ./api/db/.env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - vic-nic
  api:
    restart: on-failure:1
    container_name: vic-api
    depends_on:
      - database
    build:
      context: api
    env_file: ./api/src/.env
    ports:
      - 1080:80
      - 10443:443
    volumes:
      - "./api/certs:/root/https"
    networks:
      - vic-nic
  app:
    restart: on-failure:1
    container_name: vic-app
    tty: true
    stdin_open: true
    depends_on:
      - api
    build:
      context: app
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public
      - vic-app-node-cache:/usr/app/node_modules
    networks:
      - vic-nic

networks:
  vic-nic:
    name: vic-net
    driver: bridge

volumes:
  vic-app-node-cache:
    name: vic-app-node-cache
  database:
    name: vic-api-db
