version: "3.5"

services:
  vic-db:
    restart: always
    container_name: vic-db
    build:
      context: api/db
    env_file: ./api/db/.env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - vic
  vic-api:
    restart: always
    container_name: vic-api
    depends_on:
      - vic-db
    build:
      context: api
    env_file: ./api/src/.env
    ports:
      - 1080:80
      - 10443:443
    volumes:
      - "./api/certs:/root/https"
    networks:
      - vic
  vic-web:
    restart: always
    container_name: vic-web
    tty: true
    stdin_open: true
    depends_on:
      - vic-api
    build:
      context: app
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public
      - node-cache:/usr/app/node_modules
    networks:
      - vic

networks:
  vic:
    name: vic-net
    driver: bridge

volumes:
  node-cache:
  database:
